name: Publish Cocoapods

on:
  push:
    tags:
      - '*'

jobs:
  publish:
  
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v4
        
      - name: Deploy to Cocoapods
        run: |
          set -eo pipefail
          pod trunk push --skip-import-validation --allow-warnings --verbose
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
